### ISSUE TITLE
.vim colors looks strange

### ISSUE THREAD

**Issue by alex-popov-tech** [npxbr/gruvbox.nvim#1]
hey!
thanks for the plugin, it works great for me in lua/js/ts!
only issue is - its kinda seems a bit broken for .vim files, do you know why that could happen?
![image](https://user-images.githubusercontent.com/21224705/101514287-cac0d200-3985-11eb-9f30-376bce39ff2f.png)

**Comment by pianocomposer321** [comment]
I have this same issue...@npxbr is there a fix for this in the works?

**Comment by ellisonleao** [comment]
Yeah, vim files are still WIP , sorry about that. If you already have the hightlights figured out, please make a PR so we can track it.

**Comment by ellisonleao** [comment]
hey guys can you pull latest code and check new installation instructions and usage please? ive changed the code to use a new colorizer plugin which probably fixed that issue. Can you update and let me know ?

**Comment by ellisonleao** [comment]
Closing this since its no longer an issue. If you are still experiencing issues, just open a new one please
