### ISSUE TITLE
strings color

### ISSUE THREAD

**Issue by Stanislav-Lapata** [npxbr/gruvbox.nvim#17]
[gruvbox](https://github.com/gruvbox-community/gruvbox) dark mode has green strings on screenshot but I see white.
Is it OK?

**Comment by ellisonleao** [comment]
Color groups are still a WIP, so some groups may still be wrong

**Comment by Stanislav-Lapata** [comment]
Thanks for your quick response!

**Comment by harrygallagher4** [comment]
Actually this looks like an issue with using `unpack` [here](https://github.com/npxbr/gruvbox.nvim/blob/main/lua/gruvbox/init.lua#L274). I assume it's interacting weirdly with lush. 

Here's what the `String` highlight group says

<img width="305" alt="Screen Shot 2021-02-26 at 11 59 27 PM" src="https://user-images.githubusercontent.com/1610434/109377137-f9688d80-788e-11eb-8601-437949922134.png">

**Comment by ellisonleao** [comment]
yep, will take a look on that

**Comment by ellisonleao** [comment]
hey @harrygallagher4 @Stanislav-Lapata i did a partial which fixed that initial problem. Can you guys pull latest and try again please?

**Comment by harrygallagher4** [comment]
Looks good! By the way, when fixed this locally I used:
```lua
    String (special_string),
```
which is a bit more concise than splitting up the table into a bunch of `improved_strings_*` variables. It's sort of a hacky way to use the lush dsl though, I haven't seen that syntax used anywhere in the lush examples.

**Comment by ellisonleao** [comment]
yep, ive opened #18 to investigate special string cases.
