### ISSUE TITLE
Setting background to light

### ISSUE THREAD

**Issue by alecStewart1** [npxbr/gruvbox.nvim#2]
I'm having an issue where this plugin is setting my background to light.

I have a separate Lua file that sets the background with

```
vim.o.background = "dark"
```

If you eval this with `:lua vim.o.background = "dark"` it will correctly set the background to dark.

Removing this plugin and recompiling with packer, the background is correctly set to dark.

**Comment by ellisonleao** [comment]
you should use the api to change background. It will make sure to set this variable for you.

Something like:

```lua
require("colorbuddy").colorscheme("gruvbox", "light")
```

How's your code that sets the colorscheme and the bg?

**Comment by ellisonleao** [comment]
@alecStewart1 hey alec, now you can use the old behaviour to change colors. Please check latest README for new installation and usage instructions
