### ISSUE TITLE
Use  hsl("#...") to help your colourizer

### ISSUE THREAD

**Issue by rktjmp** [npxbr/gruvbox.nvim#22]
Not really an *issue*, but I noticed on stream :eyes: you were having trouble with `:Lushify` breaking your hexcode colourizer highlights.

This is because Lush (well, _all_ colorschemes) having to clear all highlight groups to make sure your theme updates are applied cleanly. I wrote a possible solution for colorizer here: https://github.com/norcalli/nvim-colorizer.lua/issues/35 but there hasn't been any movement in a few months.

Anyway,

If you pass your hexcodes to the HSL package, `Lushify` will correctly find and highlight them. 

There shouldn't :crossed_fingers: be any real impact on your usage, Lush will recognize the type and anywhere else *should* just coerce it back into a hexcode string.

https://github.com/npxbr/gruvbox.nvim/blob/9813ffbcda1c5738fe59b7ebce605d826656d691/lua/gruvbox/init.lua#L5

```lua
-- grab hsl package
local hsl = lush.hsl

-- later
dark0_hard = hsl("#1d2021"),
```

I want to keep `Lushify` pretty focused which is why it will *only* colourise `hsl(...)` calls.

**Comment by ellisonleao** [comment]
cool @rktjmp thanks for the tip!
