### ISSUE TITLE
g:gruvbox_invert_selection not working

### ISSUE THREAD

**Issue by pianocomposer321** [npxbr/gruvbox.nvim#24]
In my plugins.lua file I have "vim.g.gruvbox_invert_selection = 0" but it still inverts the colors of the visual selection.

![Screenshot_2021-03-11_15-48-47](https://user-images.githubusercontent.com/54072354/110859645-58f86d00-8281-11eb-9135-c444aa4b0d8d.png)

**Comment by ellisonleao** [comment]
can you try setting it to `v:false` and trying again please?

**Comment by pianocomposer321** [comment]
That works, thanks.
