### ISSUE TITLE
Inverted colors on python files when treesitter is installed

### ISSUE THREAD

**Issue by pianocomposer321** [npxbr/gruvbox.nvim#25]
When treesitter is installed and highlighting is enables, any time there is something like an unmatched parenthesis or a for loop without a colon, highlighting gets inverted and it's really distracting. Is there a way to disable this?

![Screenshot_2021-03-11_20-03-33](https://user-images.githubusercontent.com/54072354/110880874-ea2d0b00-82a4-11eb-9e68-fb5bf3f0aaeb.png)

**Comment by ellisonleao** [comment]
yeah, the error highlights for treesitter are kinda odd, specially on errors, this is a known bug which i am hoping to fix in the next few days.

**Comment by ellisonleao** [comment]
hey @pianocomposer321 ive changed the hightlight with an underline and red bold fg. Unfortunately treesitter still highlights some elements inside the original error msg and you will still see those in a different color. LMK if that makes sense.

**Comment by pianocomposer321** [comment]
Looks much better, thanks!

**Comment by timbedard** [comment]
@ellisonleao And now I'm running into the deviation from OG gruvbox in all other uses of `Error`. 😂

1. I vote we revert the `Error` highlight group to again match OG gruvbox. 

2. If I understand correctly, `TSError` highlights where Treesitter encountered a parsing error, not where there is an error in the code or where some symbol in the code is of an Error type, so it's a bit of an oddball as far as highlight groups go.

For myself, unless I'm actively working on a Treesitter parser, I don't care if it ran into a parsing error, especially given Treesitter's ability to recover and parse the rest of the file. I would much rather let it fail silently and have some words look off than light my code up like a Christmas tree.

I think the better approach here would be to link it to something unobtrusive or just not bother defining the highlight group for `TSError`.
