### ISSUE TITLE
Typescript has lots of white with treesitter

### ISSUE THREAD

**Issue by dahmc** [npxbr/gruvbox.nvim#27]
In a typescript file, there are a lot of white colors, for all the characters below:
```
.
,
[
]
(
)
{
}
|
```

In the gruvbox community, that's more of a green and fits much nicer. 

Is this intended?

**Comment by ellisonleao** [comment]
hey @dahmc can you show some screenshots and you current config please?

**Comment by dahmc** [comment]
@ellisonleao Apologies for the incomplete issue I created, I was a bit in a rush.

So, here's how it looks like with gruvbox-community:
![Screenshot 2021-03-14 at 10 16 21](https://user-images.githubusercontent.com/75008413/111063477-fa183b00-84ae-11eb-9de3-4c9576012ff5.png)


This is the same output when used with this repo:

![Screenshot 2021-03-14 at 10 17 33](https://user-images.githubusercontent.com/75008413/111063480-fedcef00-84ae-11eb-952c-94a7f9557716.png)

I import it normally, and also the gruvbox-community is commented and PlugClean has been run
```
Plug 'neoclide/coc.nvim', {'branch': 'release'}
Plug 'nvim-treesitter/nvim-treesitter', {'do': ':TSUpdate'} 

Plug 'rktjmp/lush.nvim'
Plug 'npxbr/gruvbox.nvim'
```

This is the gruvbox specific setting
```
" Gruvbox
set termguicolors
let g:gruvbox_invert_selection='0'
colorscheme gruvbox
let g:gruvbox_contrast_dark='soft'
let g:gruvbox_contrast_light='soft'
let g:gruvbox_italic=1
set background=dark
syntax enable
```

**Comment by dahmc** [comment]
Just updated to the latest tree-sitter 0.19.3 from 0.18.3, and neovim HEAD, still the same color issue

**Comment by ellisonleao** [comment]
yep, need to check which hightlights are missing and if they are with the right color

**Comment by ellisonleao** [comment]
hey @dahmc i've added some new groups highlights, but we are still missing some groups to be figured out. Are you using another typescript syntax plugin outside treesitter?

**Comment by dahmc** [comment]
@ellisonleao I only use treesitter for highlighting. If I disable it, it's pretty much all white, so there's nothing else providing syntax.

Here's my plugins and the coc extensions:
```vim
Plug 'neoclide/coc.nvim', {'branch': 'release'} 
Plug 'nvim-treesitter/nvim-treesitter', {'do': ':TSUpdate'} 
Plug 'nvim-treesitter/nvim-treesitter-textobjects'

Plug 'tpope/vim-fugitive'
Plug 'mhinz/vim-signify'
Plug 'rhysd/git-messenger.vim'
Plug 'idanarye/vim-merginal'
Plug 'junegunn/gv.vim'
Plug 'rbong/vim-flog'

Plug 'rktjmp/lush.nvim'
Plug 'npxbr/gruvbox.nvim'

Plug 'justinmk/vim-sneak'
Plug 'unblevable/quick-scope'

Plug 'itchyny/lightline.vim'

Plug 'editorconfig/editorconfig-vim'

Plug 'suy/vim-context-commentstring'
Plug 'tpope/vim-commentary'

Plug 'kyazdani42/nvim-web-devicons'
Plug 'romgrk/barbar.nvim'

" Telescope dependencies
Plug 'nvim-lua/popup.nvim'
Plug 'nvim-lua/plenary.nvim'
" Telescope
Plug 'nvim-telescope/telescope.nvim'
Plug 'nvim-telescope/telescope-fzf-writer.nvim'
Plug 'nvim-telescope/telescope-fzy-native.nvim'


"CoC Extensions
let g:coc_global_extensions = ['coc-json', 'coc-vimlsp', 'coc-tsserver', 'coc-css', 'coc-eslint', 'coc-html', 'coc-html-css-support', 'coc-powershell', 'coc-prettier', 'coc-python', 'coc-sh', 'coc-stylelintplus', 'coc-svg', 'coc-yaml', 'coc-pairs']

```

And this is my treesitter config in lua
```lua
require('nvim-treesitter.configs').setup({
    ensure_installed = "all",

    highlight = {
        enable = true,
    },

    incremental_selection = {
        enable = true,
        keymaps = {
            init_selection = "gnn",
            node_incremental = "grn",
            scope_incremental = "grc",
            node_decremental = "grm",
        },
    },

    indent = {
        enable = true
    },

		playground = {
			enable = true,
			disable = {},
			updatetime = 25, -- Debounced time for highlighting nodes in the playground from source code
			persist_queries = false -- Whether the query persists across vim sessions
		},

		textobjects = {
			select = {
				enable = true,
				keymaps = {
					-- You can use the capture groups defined in textobjects.scm
					["af"] = "@function.outer",
					["if"] = "@function.inner",
				--["ac"] = "@call.outer",
				--["ic"] = "@call.inner",
				--["as"] = "@statement.outer",

				},
			},
		},

})

```

**Comment by gshpychka** [comment]
Same issue here with Python.

**Comment by ellisonleao** [comment]
hey @gshpychka what are the chars you are having issues? can you provide some code please?

**Comment by gshpychka** [comment]
Same ones as in this issue:

![image](https://user-images.githubusercontent.com/23005347/113384628-21b44200-938f-11eb-9bfc-acc5df0c38bf.png)

And with `gruvbox-community`:

![image](https://user-images.githubusercontent.com/23005347/113384650-2e389a80-938f-11eb-87d6-bee81d1ef857.png)

**Comment by ellisonleao** [comment]
hey guys can you let me know if its okay now?

**Comment by dahmc** [comment]
@ellisonleao looks great now. Exactly the same as from the community one. Thanks a lot for fixing this!

I have now switched to this version permanently, instead of the community one. Great work!
