### ISSUE TITLE
Lightline support not working

### ISSUE THREAD

**Issue by dahmc** [npxbr/gruvbox.nvim#28]
I saw your commit to add lightline support in https://github.com/npxbr/gruvbox.nvim/commit/877451aff3f125ded1cb6c3b080d358bb5cfe112

However, when I start vim, it tells me
`lightline.vim: Could not load colorscheme gruvbox`

I did a plugin update and verified in the folder that `/lua/gruvbox/plugins/lightline.vim` exists, and it's there. 

Do I have to enable it somehow?

**Comment by ellisonleao** [comment]
hey @dahmc can you share your current config please?

**Comment by dahmc** [comment]
This is my current lightline settings: 
```
let g:lightline = {
			\ 'colorscheme': 'gruvbox',
			\ 'active': {
			\   'left': [ [ 'mode', 'paste' ],
			\             [ 'gitbranch', 'readonly', 'filename', 'modified' ] ]
			\ },
			\ 'component_function': {
			\   'gitbranch': 'FugitiveHead'
			\ },
			\ }

```

**Comment by ellisonleao** [comment]
cool i will debug it here on my side. thanks

**Comment by ellisonleao** [comment]
hey @dahmc can you pull latest and try again. We still have a loading issue showing an error msg due to the way lightline loads the script, but i could see that the highlights are working fine. LMK if you have more issues and if we can close this

**Comment by dahmc** [comment]
@ellisonleao works great. Thanks for the fix!

I don't see any error message btw :)
