### ISSUE TITLE
Add support for gruvbox_sign_column

### ISSUE THREAD

**Issue by timbedard** [npxbr/gruvbox.nvim#31]
One thing missing for compatibility is `g:gruvbox_sign_column`. I personally prefer the sign column background to be `bg0` rather than `bg1`, so I have this set. It's a bit of a hassle to go and set all the relevant sign highlight backgrounds to `bg0`.

**Comment by ellisonleao** [comment]
hey @timbedard, `g:gruvbox_sign_column` should be already supported as you can see it [here](https://github.com/npxbr/gruvbox.nvim/blob/main/lua/gruvbox/base.lua#L70) . Do you have latest code over there?

**Comment by timbedard** [comment]
Pffft. Must have mis-grepped. I'll move the option to the setup function in my packer config and see if that does it.

**Comment by timbedard** [comment]
Ah. I see the problem. The way that `get_color_from_var()` works right now, you can only set colors based on the base palette. In the original gruvbox you can set based on relative colors (such as `bg0`) as well.

**Comment by ellisonleao** [comment]
> In the original gruvbox you can set based on relative colors (such as bg0) as well.

yep, that was the issue, I will add the original behaviour to this one just to keep consistency then.

**Comment by ahnafalnafis** [comment]
> hey @timbedard, `g:gruvbox_sign_column` should be already supported as you can see it [here](https://github.com/npxbr/gruvbox.nvim/blob/main/lua/gruvbox/base.lua#L70) . Do you have latest code over there?

That link is broken. Could you please provide the new one? Thanks :heart:

**Comment by oschrenk** [comment]
@ahnafalnafis 

Now: it's part of the config

```
    require("gruvbox").setup({
      overrides = {
        SignColumn = { bg = "#282828" },
      },
    })
    vim.cmd("colorscheme gruvbox")
```
