### ISSUE TITLE
lightline support doc and screenshot

### ISSUE THREAD

**Issue by ttys3** [npxbr/gruvbox.nvim#33]
I've made one:

![gruvbox](https://user-images.githubusercontent.com/41882455/112709267-d2839280-8ef2-11eb-9751-8c8326a0d35a.png)

to use it for lightline:

```vim
let g:lightline.colorscheme = 'gruvbox'
```

if this is OK, I think I could make a PR

**Comment by ttys3** [comment]
by the way, the VISUAL mode statusbar background is diff, is this the desired result ? @ellisonleao

**Comment by ellisonleao** [comment]
I don't think we need to add screenshots for plugin supports we can just add them to the list of the supported plugins. 

As for the visual color, its using the same color patterns from the [comunnity gruvbox version](https://github.com/gruvbox-community/gruvbox/blob/master/autoload/lightline/colorscheme/gruvbox.vim#L46-L48). If you are having other issues, let's open a new issue.
