### ISSUE TITLE
colors in diffmode can be hard to see (depending on current syntax highlighting).

### ISSUE THREAD

**Issue by m-fonseca** [npxbr/gruvbox.nvim#37]
Hello!

When using the original gruvbox, diffs were very easy to see because of the background text changes.  It was kinda ugly but very easy to see.

With this implementation the diffs have no background highlighting and are nuanced (this varies depending on what syntax highlighting is going on though).  Sometimes its challenging to pick out the differences.  It might be worth considering a change in background colors.

Thanks!

**Comment by ellisonleao** [comment]
hey @m-fonseca can you show some screenshots and your current config, please?

**Comment by Mayrixon** [comment]
I might have the same problem but in a different situation.

I'm trying to config neovim 0.5 with built-in LSP. I found the bg color of floating windows when using "hover" provided by LSP is the same as the main window's bg color. However, the bg color of auto-complete floating windows looks fine.

I also tested with coc.nvim, and found the same problem.

**Comment by Mayrixon** [comment]
I've already created PR #44 to fix this problem. In morhetz/gruvbox, there is no setting for `NormalFloat` or `NormalNC`, hence Neovim would decide a default bg color. However before #44, Both `NormalFloat` and `NormalNC` are setted as `Normal` text, which means the bg color would be setted as the same as main text area's bg color. This may caused the undistinguish areas between main windows and float windows.

**Comment by ellisonleao** [comment]
hey @m-fonseca is this still an issue? please let me know

**Comment by ouuan** [comment]
> is this still an issue? please let me know

It's still an issue for me.

https://github.com/morhetz/gruvbox:
![screenshot](https://user-images.githubusercontent.com/30581822/120791965-6fa01e80-c567-11eb-90c0-bdbed84920b2.png)

gruvbox.nvim (86bc293):
![screenshot](https://user-images.githubusercontent.com/30581822/120792017-80e92b00-c567-11eb-9eff-c0f5360bddd4.png)

**Comment by m-fonseca** [comment]
Ouuan's PR fixes this problem for me.
