### ISSUE TITLE
Slow Startup Time.

### ISSUE THREAD

**Issue by marcelarie** [npxbr/gruvbox.nvim#40]
I don't know if this is an issue but I just wanted to notify it.

**[gruvbox morhetz](https://github.com/morhetz/gruvbox)** 29.296  
**[vim-gruvbox8](https://github.com/lifepillar/vim-gruvbox8)** 6.132  
**[gruvbox.nvim](https://github.com/npxbr/gruvbox.nvim)** 63.473

**Comment by ellisonleao** [comment]
hey @marcelarie how are you getting those numbers?

**Comment by marcelarie** [comment]
I don't know really, they aren't normal right?

**Comment by ellisonleao** [comment]
@marcelarie lua modules are loaded differently, you can't measure the right startup time using this plugin, unfortunately.

**Comment by marcelarie** [comment]
Then that's why, Thank you!!

**Comment by gravndal** [comment]
I'm seeing similar results running the following in my shell:
```fish
time for i in (seq 1000)
    nvim -c ':quit'
end
```

Default colorscheme (with the rest of my configuration unchanged):
```
________________________________________________________
Executed in  104.60 secs    fish           external
   usr time   74.60 secs  124.05 millis   74.47 secs
   sys time   20.18 secs  367.65 millis   19.81 secs
```

vim-gruvbox8:
```
________________________________________________________
Executed in  107.28 secs    fish           external
   usr time   76.67 secs  131.01 millis   76.53 secs
   sys time   21.06 secs  382.06 millis   20.68 secs
```

vim-gruvbox8 with `let g:gruvbox_filetype_hi_groups = 1`:
```
________________________________________________________
Executed in  108.97 secs    fish           external
   usr time   77.96 secs   97.95 millis   77.86 secs
   sys time   21.33 secs  384.21 millis   20.94 secs
```

gruvbox.nvim:
```
________________________________________________________
Executed in  125.75 secs    fish           external
   usr time   89.46 secs   92.28 millis   89.37 secs
   sys time   26.62 secs  416.94 millis   26.20 secs
```

Which honestly isn't that noticeable a difference on top of everything else, it only adds up to about a frame a 60hz. Still every little bit counts.

A clean vim for comparison:
```
________________________________________________________
Executed in   13.15 secs    fish           external
   usr time   10.12 secs   69.48 millis   10.05 secs
   sys time    3.01 secs  322.10 millis    2.69 secs
```
