### ISSUE TITLE
Red color for folders.

### ISSUE THREAD

**Issue by marcelarie** [npxbr/gruvbox.nvim#41]
In the original gruvbox this ones are green.
My terminal is kitty.
![image](https://user-images.githubusercontent.com/62728887/115967264-f22dcb00-a531-11eb-8aea-2e32ce2f931e.png)

**Comment by ellisonleao** [comment]
Are you using treesitter?

**Comment by marcelarie** [comment]
Yes.

**Comment by ellisonleao** [comment]
What plugin is this one? Nerdtree, nvim-tree, other?

**Comment by marcelarie** [comment]
Sorry I didn't give enough info from the beginning :) 
It's [nvim-tree]( https://github.com/kyazdani42/nvim-tree.lua)

**Comment by ndreas** [comment]
It's the same in the wildmenu, directories are red. The highlight group is `Directory` and it differs from the original Gruvbox:

https://github.com/npxbr/gruvbox.nvim/blob/main/lua/gruvbox/base.lua#L183
https://github.com/gruvbox-community/gruvbox/blob/master/colors/gruvbox.vim#L617

**Comment by ellisonleao** [comment]
yep, will make the fix asap
