### ISSUE TITLE
No highlighting

### ISSUE THREAD

**Issue by cydmium** [npxbr/gruvbox.nvim#48]
I am not sure what is going wrong here, but I am not getting any of the colorscheme to work. 

### Expected Behavior
Highlighting should match (at least closely) to the gruvbox by Morhetz.
Morhetz/gruvbox (expected behavior):
![gruvbox_original](https://user-images.githubusercontent.com/29664742/117863893-3d4e1a80-b262-11eb-8542-c88096cb9e49.png)

### Actual Behavior
I am not getting any correct highlighting with this plugin. I have tried using it both with and without tree sitter and termguicolors. I have also tried changing terminals; I have tried urxvt, xterm, and gnome-terminal. The behavior is identical across all 3. I have also verified that the colorscheme is being set to gruvbox through `:colorscheme`.
![gruvbox_lua](https://user-images.githubusercontent.com/29664742/117863888-3cb58400-b262-11eb-8707-ad78434d30a4.png)

### Minimal Configuration to Reproduce
``` lua
-- Auto install packer.nvim if not exists
local install_path = vim.fn.stdpath('data')..'/site/pack/packer/start/packer.nvim'
if vim.fn.empty(vim.fn.glob(install_path)) > 0 then
  vim.api.nvim_command('!git clone https://github.com/wbthomason/packer.nvim '..install_path)
end

vim.cmd [[packadd packer.nvim]]

require('packer').startup(function()
  use 'wbthomason/packer.nvim' -- packer manages itself

  use {"npxbr/gruvbox.nvim", requires = {"rktjmp/lush.nvim"}}
  -- use 'morhetz/gruvbox' -- for comparison
  use {"nvim-treesitter/nvim-treesitter", run = ":TSUpdate"} -- smart syntax highlighting
end)

vim.o.background = 'dark'
vim.cmd([[colorscheme gruvbox]])
```

**Comment by ellisonleao** [comment]
hey @cydmium, i guess you are missing the termguicolors setting. I've added `vim.o.termguicolors = true` in that config, just before the background setting and it worked.

![Screenshot from 2021-05-24 22-17-41](https://user-images.githubusercontent.com/178641/119425565-00f8d080-bcde-11eb-97f2-4b55619f07cf.png)

**Comment by cydmium** [comment]
That was the problem (well actually it was that my terminal didn't have proper true color support). I've switched terminal emulators and added the termguicolors option and everything is working as expected. Thanks!

**Comment by begss** [comment]
I guess it should be mentonied in README, just spend 15 mins trying to solve the problem until found this issue
