### ISSUE TITLE
setting variables `gruvbox_*` are useless when installed by packer.nvim

### ISSUE THREAD

**Issue by hronro** [npxbr/gruvbox.nvim#49]
I just noticed in the `settings.lua` there is:

https://github.com/npxbr/gruvbox.nvim/blob/eb5e2ae8845969d1979de9df9481ae291a6ca321/lua/gruvbox/settings.lua#L36-L41

The code above will run immediately when the plugin is loaded.

When plugins is installed by packer.nvim, neovim will loaded plugins first, and `~/.config/nvim/init.lua` will be loaded after that, so `gruvbox.nvim` read those variables before you can set them.
I'm not a expert of neovim, so maybe I'm wrong about that.

**Comment by Shivix** [comment]
Yeah, my variable changes had no effect until I put them before the ```colorsheme gruvbox```  in my config

**Comment by ellisonleao** [comment]
hey @hronro that specific part is just to set the default values first, if you look a little bit down I am making some checks again for custom global vars. About the loading order, I did not have issues so far, and I am using lua in my custom configs. Are you having any issues?

**Comment by hronro** [comment]
Hi @ellisonleao, sorry for the delay. I'm setting `gruvbox_contrast_dark ` with `vim.api.nvim_set_var('gruvbox_contrast_dark', 'hard')`, but it does not work at all. Are you able to set `gruvbox_contrast_dark `?
