### ISSUE TITLE
Feature request : transparency 

### ISSUE THREAD

**Issue by danielnehrig** [npxbr/gruvbox.nvim#52]
title
basically removing background colors guibg

**Comment by cvignal** [comment]
Add `hi Normal guibg=NONE ctermbg=NONE` to your `init.vim` or `vim.cmd([[hi Normal guibg=NONE ctermbg=NONE]])` to your `init.lua` and it should work.

**Comment by ellisonleao** [comment]
unfortunately this is a not a feature in this plugin. You can try the suggestion from @cvignal and it should probably work just fine
