### ISSUE TITLE
Breaking with latest lush.nvim

### ISSUE THREAD

**Issue by sQVe** [npxbr/gruvbox.nvim#54]
Hey 👋🏼,

Cheers for an awesome colorscheme! I just now ran an update and `lush.nvim` was updated. Since then `gruvbox.nvim` is broken and erroring with:

```
packer.nvim: Error running config for gruvbox.nvim: [string "..."]:0: Vim(lua):E5108: Error executing lua ...site/pack/packer/start/gru
vbox.nvim/lua/gruvbox/base.lua:2: module 'lush.hsl.convert' not found:
^Ino field package.preload['lush.hsl.convert']
^Ino file './lush/hsl/convert.lua'
^Ino file '/usr/share/luajit-2.0.5/lush/hsl/convert.lua'
^Ino file '/usr/local/share/lua/5.1/lush/hsl/convert.lua'
^Ino file '/usr/local/share/lua/5.1/lush/hsl/convert/init.lua'
^Ino file '/usr/share/lua/5.1/lush/hsl/convert.lua'
^Ino file '/usr/share/lua/5.1/lush/hsl/convert/init.lua'
^Ino file '/home/sqve/.cache/nvim/packer_hererocks/2.0.5/share/lua/5.1/lush/hsl/convert.lua'
^Ino file '/home/sqve/.cache/nvim/packer_hererocks/2.0.5/share/lua/5.1/lush/hsl/convert/init.lua'
^Ino file '/home/sqve/.cache/nvim/packer_hererocks/2.0.5/lib/luarocks/rocks-5.1/lush/hsl/convert.lua'
^Ino file '/home/sqve/.cache/nvim/packer_hererocks/2.0.5/lib/luarocks/rocks-5.1/lush/hsl/convert/init.lua'
^Ino file './lush/hsl/convert.so'
^Ino file '/usr/local/lib/lua/5.1/lush/hsl/convert.so'
^Ino file '/usr/lib/lua/5.1/lush/hsl/convert.so'
^Ino file '/usr/local/lib/lua/5.1/loadall.so'
^Ino file '/home/sqve/.cache/nvim/packer_hererocks/2.0.5/lib/lua/5.1/lush/hsl/convert.so'
^Ino file './lush.so'
^Ino file '/usr/local/lib/lua/5.1/lush.so'
^Ino file '/usr/lib/lua/5.1/lush.so'
^Ino file '/usr/local/lib/lua/5.1/loadall.so'
```

**Comment by jared-mackey** [comment]
Seeing this as well. Looks like @rktjmp has been making a lot of changes there today. They could maybe provide some insight on how to fix :)

**Comment by rktjmp** [comment]
You can just call `my_color.hex` (or `tostring(my_color)`) instead of accessing the (theoretically private-ish) converter directly.

**Comment by rktjmp** [comment]
Nb you can pin to 684c06d4879a38e50a247ce23b32beaacc75c4d1 while waiting for the patch to merge if you don't want to use the PR branch directly.

All the new stuff in Lush is around a new colourspace and some new color operations which gruvbox doesn't use anyway.

**Comment by h4rr9** [comment]
`require('lush.vivid.hsl.convert')` in base.lua seems to do the trick, assuming its just a simple refactor..

**Comment by rktjmp** [comment]
I have added a temporary alias to lush so everyone's gruvbox keeps working until the mentioned PR is merged 'cause I know how frustrating it is to have our meticulously configured environment's just break.

Please stick to to the documented API when possible though and raise an issue if it doesn't cover a specific need. Adjusting to use `require('lush.vivid.hsl.convert')` will only break again on the next release. The `.hex/tostring()/concat` functions have always been the documented method.
