### ISSUE TITLE
Background of 'sign' is Highlighted 

### ISSUE THREAD

**Issue by spamwax** [npxbr/gruvbox.nvim#61]
I am not sure if this is intended behavior or it's caused by `signify` plugin, but shouldn't the background of sign not be modified by themes.

This is what I get from `gruvbox.nvim`:
<img width="149" alt="Screen Shot 2021-07-27 at 7 22 06 PM" src="https://user-images.githubusercontent.com/1251233/127241580-0a990ad6-ad00-4f43-8973-05dd914bf6ae.png">
As seen, the entire sign row/column has a lighter background where the git-add symbol is inserted!

This is the (correct?) behavior of [snazzy](https://github.com/bbenzikry/snazzybuddy.nvim) theme:
<img width="219" alt="Screen Shot 2021-07-27 at 7 24 18 PM" src="https://user-images.githubusercontent.com/1251233/127241560-7ecdc6a5-4080-4cae-894e-6ab9d5d756cb.png">

It this expected? any way of working around it?

**Comment by ellisonleao** [comment]
hey @spamwax can you compare with the [gruvbox-community](https://github.com/gruvbox-community/gruvbox/) version and check if its the same output? This plugin is a direct copy of the original one in vimscript

**Comment by spamwax** [comment]
@ellisonleao 
Yea, community version behaves like the screenshots above. 
I guess it's a matter of preference. I personally don't like the highlighted one since it breaks away from the rest of the background.

Is there anything highlight group or setting that I can use to change it?

**Comment by ellisonleao** [comment]
I think the option is only available on the original version, through [`g:gruvbox_sign_column` var](https://github.com/morhetz/gruvbox/wiki/Configuration#ggruvbox_sign_column). The community version, which this plugin is based from, doesn't have this option

**Comment by uunnxx** [comment]
What you ended up doing? @spamwax 
I have the same issue, and tired by searching solutions...

**Comment by uunnxx** [comment]
> I think the option is only available on the original version, through [`g:gruvbox_sign_column` var](https://github.com/morhetz/gruvbox/wiki/Configuration#ggruvbox_sign_column). The community version, which this plugin is based from, doesn't have this option

@ellisonleao  what we could do ?

**Comment by spamwax** [comment]
@uunnxx I ended up switching to `gruvbox-material` theme.
