### ISSUE TITLE
Performance comparison with VimL version

### ISSUE THREAD

**Issue by spamwax** [npxbr/gruvbox.nvim#62]
Using [startuptime](https://github.com/tweekmonster/startuptime.vim) plugin, I compared the load time of Lua-based gruvbox to the community version:

1. gruvbox.nvim

```config
Slowest 10 plugins (out of 42)~
            [unknown]	47.137  
         gruvbox.nvim	18.072  
            [runtime]	12.338  
             coc.nvim	5.541   
```

2. gruvbox-community

```config
Slowest 10 plugins (out of 42)~
            [unknown]	47.240  
            [runtime]	12.291  
              gruvbox	8.288   
             coc.nvim	5.355   
```

**Comment by ellisonleao** [comment]
Lua plugins are loaded in a different way, so you really can't use this plugin to measure the real performance. If you use packer.nvim, you can have some real results using the [profiling](https://github.com/wbthomason/packer.nvim#profiling) options
