### ISSUE TITLE
[General hint request] Some text has blurry font

### ISSUE THREAD

**Issue by dzintars** [npxbr/gruvbox.nvim#63]
Hi.
I's absolutely sure this is not the issue of this particular theme/plugin.
But me, and possible some other could find it helpful.
![image](https://user-images.githubusercontent.com/547420/129557966-5eb069ed-67ae-49ad-b847-ef92aab26c7f.png)
As you can see in the image, some symbols have blurry text, and i can't figure out what could cause that.
I am using Alacritty with Nerd Hack font size 9.0. Wayland/Sway.
No zooming applied. Even if i do apply zoom, it has no effect and some text is still blurry. I tried to change terminal font and it's size as well.
I believe it's could be related to subpixel rendering, but not fully sure.
Would be thankful for any hints. 😺

**Comment by ellisonleao** [comment]
no idea man, but it's definitely not related to this plugin.
