### ISSUE TITLE
colorscheme should not use top namespace

### ISSUE THREAD

**Issue by wsdjeg** [npxbr/gruvbox.nvim#7]
not same as normal plugin, colorscheme should not use top namespace.

**Comment by ellisonleao** [comment]
hey @wsdjeg not sure if i understood the problem. Can you give more context please?

**Comment by wsdjeg** [comment]
hmm, sorry. I think colorscheme should use `colorscheme.gruvbox` namespace. because someone colorscheme has too general name, for example `sting` which is data type,  `red` which is a name of programming language.

**Comment by ellisonleao** [comment]
Sorry @wsdjeg i still don't understood the problem. Is this about the lua modules? can you show some code where the problem occurs?
