### ISSUE TITLE
Missing terminal colors

### ISSUE THREAD

**Issue by kristijanhusak** [npxbr/gruvbox.nvim#8]
Hi,

I noticed that terminal colors are missing (see `:helpgrep terminal_color_`).
I'm not sure if colorbuddy should provide that or not, but they are not defined at all.

**Comment by ellisonleao** [comment]
hey @kristijanhusak, yes they are not defined. From what i saw in the docs, it seems the color highlights are just forwared to the terminal mode, if defined in other highlight groups. Do you have any bug happening now?

**Comment by kristijanhusak** [comment]
hey @ellisonleao , can you point me to the docs where it explains how it works? From my tests, only background color is picked up. Other terminal colors are taken from the terminal emulator colors.

I'm using a small python script to generate kitty terminal colors from the colorscheme. Script reads `g:terminal_color` values and generates the colorscheme from that. Here's the link if you're interested: https://gist.github.com/kristijanhusak/2039c3cca4a574c5521e39b4d0c5ce66. In this case it doesn't work because those variables are not defined.

Here's the screenshot:
![screenshot](https://i.imgur.com/iPhOuxS.png)

On the left is neovim instance with gruvbox colorscheme with opened terminal, where on right is my kitty terminal with it's own colors. If you look closely you'll notice that only background color is picked up by neovim terminal, and other colors are exactly the same like from the kitty terminal colorscheme. I would expect neovim terminal instance to have it's own colors, which it does when I tried it with the gruvbox-community/gruvbox color scheme.

**Comment by ellisonleao** [comment]
hey @kristijanhusak , i've created a new code, using another colorizer plugin and ive added those global variables as well. Can you check latest code and see if it works properly now please?

**Comment by kristijanhusak** [comment]
Hey @ellisonleao , i gave it a test, but it's not working.
It even breaks initialization of nvim-tree plugin because it depends on some of these colors.
When I tried to check what are the values of these colors, it turns out they are tables instead of strings.

For example, this:
```
:lua print(vim.inspect(vim.g.terminal_color_0))
```

prints an empty table. This should either be a string with hex color in it, or not defined at all.

**Comment by ellisonleao** [comment]
ok i will debug it here and let you know. Thanks for the feedback

**Comment by ellisonleao** [comment]
@kristijanhusak just pushed a fix. Lmk if that worked on your side

**Comment by kristijanhusak** [comment]
Looks good now, thanks!
